### ISSUE TITLE
'BERTEmbedder' object has no attribute 'embedding_dim'

### ISSUE THREAD

**Issue by TaiJuWu** [begab/sparsity_makes_sense#1]
I have a question:
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    cli_main()
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/fairseq_cli/train.py", line 68, in main
    model = task.build_model(args)
  File "/home/nlplab/tjwu/ewiser/ewiser/fairseq_ext/tasks/sequence_tagging.py", line 140, in build_model
    model = super().build_model(args)
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 270, in build_model
    model = models.build_model(args, self)
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/fairseq/models/__init__.py", line 58, in build_model
    return ARCH_MODEL_REGISTRY[model_cfg.arch].build_model(model_cfg, task)
  File "/home/nlplab/tjwu/ewiser/ewiser/fairseq_ext/models/sequence_tagging.py", line 257, in build_model
    decoder = cls.build_model_decoder(args, task.dictionary, task.output_dictionary, FakeInput(embedder.embedding_dim))
  File "/home/nlplab/tjwu/anaconda3/envs/ewiser/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'BERTEmbedder' object has no attribute 'embedding_dim'

Can you tell me how to solve?
I have restore sensebert+ LMMS embeddings in res/embeddings

**Comment by begab** [comment]
The error you mention seems to be related to a different repository (in particular, your error is seemingly related to this line of code: https://github.com/SapienzaNLP/ewiser/blob/98932533bc9edf858808aa5ec9d39d1b9472644e/bin/train.py#L16).
Maybe you could ask the authors of that other repo.
